#!/usr/bin/env python
import optparse
import sys
import models
from collections import namedtuple
import pdb

optparser = optparse.OptionParser()
optparser.add_option("-i", "--input", dest="input", default="data/input", help="File containing sentences to translate (default=data/input)")
optparser.add_option("-t", "--translation-model", dest="tm", default="data/tm", help="File containing translation model (default=data/tm)")
optparser.add_option("-l", "--language-model", dest="lm", default="data/lm", help="File containing ARPA-format language model (default=data/lm)")
optparser.add_option("-n", "--num_sentences", dest="num_sents", default=sys.maxint, type="int", help="Number of sentences to decode (default=no limit)")
optparser.add_option("-k", "--translations-per-phrase", dest="k", default=1, type="int", help="Limit on number of translations to consider per phrase (default=1)")
optparser.add_option("-r", "--reordering-limit", dest="r", default=1, type="int", help="Reordering limit (default=1)")
optparser.add_option("-s", "--stack-size", dest="s", default=1, type="int", help="Maximum stack size (default=1)")
optparser.add_option("-v", "--verbose", dest="verbose", action="store_true", default=False,  help="Verbose mode (default=off)")
opts = optparser.parse_args()[0]

tm = models.TM(opts.tm, opts.k)
lm = models.LM(opts.lm)
french = [tuple(line.strip().split()) for line in open(opts.input).readlines()[:opts.num_sents]]

# tm should translate unknown words as-is with probability 1
for word in set(sum(french,())):
  if (word,) not in tm:
    tm[(word,)] = [models.phrase(word, 0.0)]

def iter_index_sublists(indices):
  """Iterates index sublists all of whose indices are consecutive."""
  n = len(indices) + 1
  for i in xrange(n):
    for j in xrange(i + 1, n):
      sublist = indices[i:j]
      diffs = [sublist[k] - sublist[k - 1] for k in xrange(1, len(sublist))]
      if (all([diff == 1 for diff in diffs])):
        yield sublist

sys.stderr.write("Decoding %s...\n" % (opts.input,))
for f in french:
  # The following code implements a monotone decoding
  # algorithm (one that doesn't permute the target phrases).
  # Hence all hypotheses in stacks[i] represent translations of 
  # the first i words of the input sentence. You should generalize
  # this so that they can represent translations of *any* i words.
  hypothesis = namedtuple("hypothesis", "logprob, lm_state, predecessor, phrase, f_indices_used")
  initial_hypothesis = hypothesis(0.0, lm.begin(), None, None, (-1,))
  stacks = [{} for _ in f] + [{}]
  stacks[0][(lm.begin(), (-1,))] = initial_hypothesis
  for i, stack in enumerate(stacks[:-1]):
    if opts.verbose:
      print("\ni = %d" % i)
    for h in sorted(stack.itervalues(),key=lambda h: -h.logprob)[:opts.s]: # prune
      if opts.verbose:
        print("hyp: %s" % str((h.logprob, h.lm_state, h.f_indices_used)))
      valid_indices = [j for j in xrange(len(f)) if j not in h.f_indices_used]  # new phrase must not include already-used words
      for phrase_indices in iter_index_sublists(valid_indices):
        f_indices_used = h.f_indices_used + tuple(phrase_indices)     
        n = len(f_indices_used)  
        if ((len(stacks[n - 1]) == 0) or (abs(h.f_indices_used[-1] - phrase_indices[0]) <= opts.r)):  # new phrase must be within reordering limit, unless stack is empty, in which case it must get an element; note: this violates the reordering limit, but it is necessary in order to use all the foreign phrases
          foreign_phrase = tuple([f[j] for j in phrase_indices])
          if foreign_phrase in tm:
            if opts.verbose:
              print((phrase_indices, foreign_phrase))
            for phrase in tm[foreign_phrase]:
              logprob = h.logprob + phrase.logprob
              lm_state = h.lm_state
              for word in phrase.english.split():
                (lm_state, word_logprob) = lm.score(lm_state, word)
                logprob += word_logprob
              logprob += lm.end(lm_state) if n == len(f) + 1 else 0.0
              new_hypothesis = hypothesis(logprob, lm_state, h, phrase, f_indices_used)
              if (lm_state, tuple(sorted(f_indices_used))) not in stacks[n - 1] or stacks[n - 1][(lm_state, tuple(sorted(f_indices_used)))].logprob < logprob: # second case is recombination
                stacks[n - 1][(lm_state, tuple(sorted(f_indices_used)))] = new_hypothesis 
  winner = max(stacks[-1].itervalues(), key=lambda h: h.logprob)
  def extract_english(h): 
    return "" if h.predecessor is None else "%s%s " % (extract_english(h.predecessor), h.phrase.english)
  print extract_english(winner)

  if opts.verbose:
    sys.stderr.write("stack sizes: %s\n" % str([len(stack) for stack in stacks]))
    def extract_tm_logprob(h):
      return 0.0 if h.predecessor is None else h.phrase.logprob + extract_tm_logprob(h.predecessor)
    tm_logprob = extract_tm_logprob(winner)
    sys.stderr.write("LM = %f, TM = %f, Total = %f\n" % 
      (winner.logprob - tm_logprob, tm_logprob, winner.logprob))
